# Lawsker系统告警规则
groups:
  - name: lawsker.rules
    rules:
      # 高错误率告警
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: lawsker-backend
        annotations:
          summary: "高错误率检测到"
          description: "错误率为 {{ $value }} 错误/秒，超过阈值"

      # API响应时间过长
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 3
        for: 5m
        labels:
          severity: warning
          service: lawsker-backend
        annotations:
          summary: "API响应时间过长"
          description: "95%分位数响应时间为 {{ $value }}秒"

      # 数据库连接数过高
      - alert: DatabaseConnectionHigh
        expr: pg_stat_database_numbackends > 80
        for: 1m
        labels:
          severity: warning
          service: postgres
        annotations:
          summary: "数据库连接数过高"
          description: "当前连接数: {{ $value }}"

      # 数据库死锁检测
      - alert: DatabaseDeadlocks
        expr: increase(pg_stat_database_deadlocks[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: postgres
        annotations:
          summary: "数据库死锁检测"
          description: "检测到 {{ $value }} 个死锁"

      # Redis内存使用率过高
      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis内存使用率过高"
          description: "内存使用率: {{ $value | humanizePercentage }}"

      # Redis连接数过高
      - alert: RedisConnectionHigh
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis连接数过高"
          description: "当前连接数: {{ $value }}"

      # 磁盘空间不足
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "磁盘空间不足"
          description: "磁盘使用率超过90%，剩余空间: {{ $value | humanizePercentage }}"

      # CPU使用率过高
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "CPU使用率过高"
          description: "CPU使用率: {{ $value }}%"

      # 内存使用率过高
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.9
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "内存使用率过高"
          description: "内存使用率: {{ $value | humanizePercentage }}"

      # 服务不可用
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "服务不可用"
          description: "{{ $labels.job }} 服务已停止"

      # NGINX错误率过高
      - alert: NginxHighErrorRate
        expr: rate(nginx_http_requests_total{status=~"4..|5.."}[5m]) / rate(nginx_http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: nginx
        annotations:
          summary: "NGINX错误率过高"
          description: "错误率: {{ $value | humanizePercentage }}"

      # 容器重启频繁
      - alert: ContainerRestartHigh
        expr: increase(container_start_time_seconds[1h]) > 3
        for: 0m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "容器重启频繁"
          description: "容器 {{ $labels.name }} 在1小时内重启了 {{ $value }} 次"

      # Elasticsearch集群状态异常
      - alert: ElasticsearchClusterRed
        expr: elasticsearch_cluster_health_status{color="red"} == 1
        for: 0m
        labels:
          severity: critical
          service: elasticsearch
        annotations:
          summary: "Elasticsearch集群状态异常"
          description: "集群状态为红色，存在不可用的分片"

      # 业务指标告警
      - alert: LowUserRegistration
        expr: increase(user_registrations_total[1h]) < 5
        for: 0m
        labels:
          severity: info
          service: business
        annotations:
          summary: "用户注册量过低"
          description: "过去1小时用户注册量: {{ $value }}"

      - alert: HighPaymentFailureRate
        expr: rate(payment_failures_total[5m]) / rate(payment_attempts_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "支付失败率过高"
          description: "支付失败率: {{ $value | humanizePercentage }}"

      # 安全告警
      - alert: SuspiciousLoginAttempts
        expr: increase(failed_login_attempts_total[5m]) > 10
        for: 0m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "可疑登录尝试"
          description: "5分钟内失败登录尝试: {{ $value }} 次"

      - alert: RateLimitExceeded
        expr: increase(rate_limit_exceeded_total[1m]) > 100
        for: 0m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "限流触发频繁"
          description: "1分钟内限流触发: {{ $value }} 次"