"""Add lawyer qualification and letter service models

Revision ID: 2a1d8d0f1ba4
Revises: 940b959512f7
Create Date: 2025-07-05 00:22:16.293711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1d8d0f1ba4'
down_revision = '940b959512f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 