groups:
  - name: lawsker_alerts
    rules:
      # 系统级告警
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高CPU使用率"
          description: "CPU使用率超过80%持续5分钟"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高内存使用率"
          description: "内存使用率超过85%持续5分钟"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高磁盘使用率"
          description: "磁盘使用率超过85%持续5分钟"

      # 应用级告警
      - alert: BackendDown
        expr: up{job="lawsker-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "后端服务宕机"
          description: "Lawsker后端服务已停止运行"

      - alert: FrontendDown
        expr: up{job="lawsker-frontend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "前端服务宕机"
          description: "Lawsker前端服务已停止运行"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "响应时间过高"
          description: "95%的请求响应时间超过2秒"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "错误率过高"
          description: "HTTP 5xx错误率超过5%"

      # 数据库告警
      - alert: DatabaseConnectionFailed
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "数据库连接失败"
          description: "PostgreSQL数据库连接失败"

      - alert: HighDatabaseConnections
        expr: pg_stat_activity_count > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "数据库连接数过高"
          description: "活跃数据库连接数超过100"

      # SSL证书告警
      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL证书即将过期"
          description: "SSL证书将在30天内过期"

      # 网络告警
      - alert: HighNetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "网络错误率过高"
          description: "网络接收错误率过高" 