# Prometheus生产环境配置
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lawsker-prod'
    replica: 'prometheus-1'

# 告警规则文件
rule_files:
  - "rules/lawsker-alerts.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# 数据采集配置
scrape_configs:
  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Lawsker后端监控
  - job_name: 'lawsker-backend'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Lawsker前端监控
  - job_name: 'lawsker-frontend'
    static_configs:
      - targets: ['localhost:6060']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']

  # SSL证书监控
  - job_name: 'ssl-certificates'
    static_configs:
      - targets: ['localhost:9115']
    metrics_path: '/probe'
    params:
      module: [http_2xx]
      target: ['lawsker.com']

# 远程写入配置（可选，用于长期存储）
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# 存储配置
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB